version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:80"
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test
    volumes:
      - ./mock-data.sql:/docker-entrypoint-initdb.d/data.sql